services:
  mysql:
    image: mysql
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  woocommerce:
    build: .
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=app
      - WORDPRESS_DB_NAME=wp
      - WORDPRESS_TABLE_PREFIX=wp
      - WORDPRESS_DEBUG=1
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
    volumes:
      - ./bharatx-pay-in-3-plugin:/var/www/html/wp-content/plugins/bharatx-pay-in-3-plugin
    depends_on:
      - mysql
    ports:
      - 8090:80

  php:
    image: php:8.1.21-fpm
    volumes:
      - ./bharatx-pay-in-3-plugin:/var/www/html/wp-content/plugins/bharatx-pay-in-3-plugin

networks:
  default:
    name: "wordpress-plugin-dev-network"
    driver: "bridge"
